pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - check-success=tests
      - author=gador
    actions:
      merge:
        method: merge
      delete_head_branch: {}
