"""add last checked

Revision ID: a8a0f243d7cd
Revises: b807041898dd
Create Date: 2022-05-08 09:38:16.626345

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a8a0f243d7cd"
down_revision = "b807041898dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("packages", sa.Column("last_checked", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("packages", "last_checked")
    # ### end Alembic commands ###
