"""move unique constraint

Revision ID: b5b577ca45b3
Revises: f875eee40428
Create Date: 2022-06-03 11:48:49.924965

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "b5b577ca45b3"
down_revision = "f875eee40428"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("packages", schema=None) as batch_op:
        batch_op.drop_index("ix_packages_name")
        batch_op.create_index(batch_op.f("ix_packages_name"), ["name"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("packages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_packages_name"))
        batch_op.create_index("ix_packages_name", ["name"], unique=False)

    # ### end Alembic commands ###
