"""add arch to persistent config

Revision ID: b5dd66973c43
Revises: eeb522bbc0ff
Create Date: 2022-06-10 12:13:07.999390

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b5dd66973c43"
down_revision = "eeb522bbc0ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("persistent_config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("archs_to_check", sa.String(length=256), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("persistent_config", schema=None) as batch_op:
        batch_op.drop_column("archs_to_check")

    # ### end Alembic commands ###
