"""initial db

Revision ID: b807041898dd
Revises:
Create Date: 2022-05-06 15:15:05.370541

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b807041898dd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "packages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("hydra_status", sa.Boolean(), nullable=True),
        sa.Column("build_url", sa.String(length=128), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_packages_name"), "packages", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_packages_name"), table_name="packages")
    op.drop_table("packages")
    # ### end Alembic commands ###
