"""add persistent config

Revision ID: eeb522bbc0ff
Revises: b5b577ca45b3
Create Date: 2022-06-04 11:40:20.579275

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eeb522bbc0ff"
down_revision = "b5b577ca45b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persistent_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("maintainer", sa.String(length=64), nullable=True),
        sa.Column("nixpkgs_path", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("persistent_config", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_persistent_config_maintainer"), ["maintainer"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("persistent_config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_persistent_config_maintainer"))

    op.drop_table("persistent_config")
    # ### end Alembic commands ###
