"""add arch

Revision ID: f875eee40428
Revises: a8a0f243d7cd
Create Date: 2022-06-02 21:34:13.417283

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f875eee40428"
down_revision = "a8a0f243d7cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("packages", sa.Column("arch", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("packages", "arch")
    # ### end Alembic commands ###
