name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: |
          nixpkgs=channel:nixos-unstable
    - run: |
        nix build -L .#checks.x86_64-linux.pytest
        cp -v result/.coverage .
        ROOTPATH=$(cat result/srcpath)
        nix run nixpkgs#python310Packages.coveralls -- --service=github --basedir=$ROOTPATH --srcdir=src
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
